window.allGenes = [
	"Abstraction (DO NOT USE)",
	"Conceptual",
	"Expressive",
	"Realism",
	"Career Stage Gene",
	"Unspecified Ceramics",
	"Glass",
	"Installation",
	"Mixed-Media",
	"Painting",
	"Performance",
	"Photography",
	"Sculpture",
	"Work on Paper/Print",
	"Monochromatic",
	"Pre-Impressionism/Old Masters",
	"Modern",
	"Contemporary",
	"Abstract Expressionism",
	"Collage",
	"Art Deco",
	"Art Informel",
	"Art Nouveau",
	"Arte Povera",
	"Arts and Crafts Movement",
	"Ashcan School",
	"\"Bad Painting\"",
	"Bloomsbury Group",
	"Barbizon School",
	"Bauhaus",
	"Body Art",
	"Color Field Painting",
	"Comic/Cartoon",
	"Constructivism",
	"Cubism",
	"Dada",
	"De Stijl",
	"East Village Art",
	"Fauvism",
	"Fluxus",
	"Folk Art",
	"Futurism",
	"Group Zero",
	"Gutai Art Group",
	"Harlem Renaissance",
	"Hudson River School",
	"Impressionism",
	"Institutional Critique",
	"Kinetic Sculpture",
	"Luminism",
	"Mexican Mural School",
	"Minimalism",
	"Nabis",
	"Native American Art",
	"Neo-Dada",
	"Neo-Expressionism",
	"Neue Sachlichkeit",
	"New York School",
	"Nouveau Realisme",
	"Outsider Art",
	"Pattern and Decoration",
	"Photorealistic",
	"Pictorialism",
	"Pointillism",
	"Post-Impressionism",
	"Postminimalism",
	"Purism",
	"Romanticism",
	"Mosaics",
	"Pittura Metafisica",
	"Social Realism",
	"Socialist Realism",
	"Surrealism",
	"Symbolism",
	"Synchronism",
	"Tonalism",
	"Metallic",
	"Viennese Workshop",
	"WPA works",
	"Young British Artists (YBA)",
	"Cityscape",
	"Human Figure",
	"Landscape",
	"Portrait",
	"Still Life",
	"Building",
	"Cyberculture",
	"Documentary Photography",
	"Fashion Photography",
	"Feminist Art",
	"Gender Politics",
	"Identity Politics",
	"Isolation/Alienation",
	"Woodcut/Linocut",
	"Outdoor Sculpture",
	"Political",
	"Baroque",
	"Mannerism",
	"Conceptual Art",
	"Dutch and Flemish",
	"Viennese Actionism",
	"Byzantine Art",
	"Waterscape",
	"Interiors",
	"Automatism",
	"Chiaroscuro",
	"Dynamism",
	"Caribbean",
	"Oceania",
	"Figurative Sculpture",
	"Contemporary Photographic Portraiture",
	"Flora",
	"Contemporary Figurative Painting",
	"Popular Culture",
	"Animals",
	"Nude",
	"Suprematism",
	"Renaissance",
	"Rough",
	"Assemblage",
	"Purism Influence",
	"Art Informel Influence",
	"\"Bad Painting\" Influence",
	"Group Zero Influence",
	"Fluxus Influence",
	"Folk Art Influence",
	"Luminism Influence",
	"Mexican Mural School Influence",
	"Native American Art Influence",
	"Neue Sachlichkeit Influence",
	"New York School Influence",
	"Nouveau Realisme Influence",
	"Pictorialism Influence",
	"Post-Impressionism Influence",
	"Romanticism Influence",
	"Social Realism Influence",
	"Socialist Realism Influence",
	"Symbolism Influence",
	"Synchronism Influence",
	"Tonalism Influence",
	"WPA works Influence",
	"Classicism Influence",
	"Byzantine Influence",
	"Suprematism Influence",
	"Renaissance Influence",
	"Arts and Crafts Movement Influence",
	"Bloomsbury Group Influence",
	"Light and Space Movement Influence",
	"East Village Art Influence",
	"Gutai Art Group Influence",
	"Harlem Renaissance Influence",
	"Pattern and Decoration Influence",
	"Pittura Metafisica Influence",
	"Viennese Workshop Influence",
	"Dutch and Flemish Influence",
	"Viennese Actionism Influence",
	"Abstract Expressionism Influence",
	"Art Deco Influence",
	"Art Nouveau Influence",
	"Arte Povera Influence",
	"Ashcan School Influence",
	"Barbizon School Influence",
	"Baroque Influence",
	"Bauhaus Influence",
	"Body Art Influence",
	"Color Field Painting Influence",
	"Conceptual Art Influence",
	"Constructivism Influence",
	"Cubism Influence",
	"Dada Influence",
	"De Stijl Influence",
	"Fauvism Influence",
	"Futurism Influence",
	"Hudson River School Influence",
	"Impressionism Influence",
	"Mannerism Influence",
	"Minimalism Influence",
	"Nabis Influence",
	"Neo-Dada Influence",
	"Neo-Expressionism Influence",
	"Outsider Art Influence",
	"Photorealism Influence",
	"Pointillism Influence",
	"Postminimalism Influence",
	"Surrealism Influence",
	"Young British Artists (YBA) Influence",
	"Assemblage Influence",
	"Influenced by Andy Warhol",
	"Influenced by Marcel Duchamp",
	"Influenced by Pablo Picasso",
	"Influenced by Paul Cézanne",
	"Influenced by Jasper Johns",
	"Influenced by Robert Rauschenberg",
	"Influenced by Josef Albers",
	"Influenced by John Cage",
	"Influenced by Merce Cunningham",
	"Influenced by Leonardo da Vinci",
	"Influenced by Jean Dubuffet",
	"Influenced by Walker Evans",
	"Influenced by Lisette Model",
	"Influenced by Bernd and Hilla Becher",
	"Modernist Photography",
	"Influenced by Robert Henri",
	"Japonisme",
	"Influenced by Alfred Stieglitz",
	"Influenced by Gustave Courbet",
	"Conflict",
	"Influenced by Barnett Newman",
	"Influenced by Paul Klee",
	"Influenced by Piet Mondrian",
	"Influenced by Henri Matisse",
	"Influenced by Lucian Freud",
	"Influenced by Constantin Brancusi",
	"Influenced by Jean Arp",
	"Influenced by Kasimir Malevich",
	"Influenced by Arshile Gorky",
	"The Artist's Studio",
	"Color Histogram 0 Hue",
	"Color Histogram 0 Saturation",
	"Color Histogram 0 Lightness",
	"Color Histogram 0 Coverage",
	"Color Histogram 1 Hue",
	"Color Histogram 1 Saturation",
	"Color Histogram 1 Lightness",
	"Color Histogram 1 Coverage",
	"Color Histogram 2 Hue",
	"Color Histogram 2 Saturation",
	"Color Histogram 2 Lightness",
	"Color Histogram 2 Coverage",
	"Influenced by Salvador Dalí",
	"Group f/64",
	"Photojournalism",
	"Americana",
	"Suburbia",
	"Rural Life",
	"Related to Fashion",
	"Anthropomorphism",
	"Humor",
	"Impasto",
	"Calligraphic",
	"En plein air",
	"Modernizing of Traditional Technique",
	"Self-Portrait",
	"Glamour",
	"Unspecified Textiles",
	"The Pictures Generation",
	"The Pictures Generation Influence",
	"Feminist Art Influence",
	"Group f/64 Influence",
	"Modernist Photography Influence",
	"Op Art",
	"Op Art Influence",
	"Biomorphic",
	"Erotic",
	"Grotesque",
	"Mortality",
	"Youth",
	"Nostalgia",
	"Nature",
	"Medical/Health",
	"Crime",
	"Contemporary Conceptualism",
	"Time",
	"Appropriation",
	"Influenced by Édouard Manet",
	"Influenced by Albrecht Dürer",
	"Influenced by Willem de Kooning",
	"Influenced by Chuck Close",
	"Influenced by John Baldessari",
	"Influenced by Francis Picabia",
	"Influenced by Giorgio de Chirico",
	"School of London",
	"School of London Influence",
	"Nineteenth Century French Realism",
	"Nineteenth Century French Realism Influence",
	"American Realism",
	"American Realism Influence",
	"American Modernism",
	"American Modernism Influence",
	"Illustration/Art",
	"Influenced by Henri Cartier-Bresson",
	"Influenced by Rembrandt",
	"Influenced by Vincent van Gogh",
	"Influenced by Diane Arbus",
	"Influenced by Edgar Degas",
	"Influenced by Mark Rothko",
	"Contemporary Gothic",
	"Contemporary Grotesque",
	"Performance Art",
	"Performance Art Influence",
	"Video Art",
	"Video Art Influence",
	"Influenced by Egon Schiele",
	"Process-Oriented",
	"Kitsch",
	"Design and Decorative Arts",
	"Psychedelic",
	"Use of Ephemeral Materials",
	"Use of Organic Material",
	"Narrative",
	"Artwork Iconicity",
	"Influenced by Gerhard Richter",
	"Influenced by Ed Ruscha",
	"Influenced by Bruce Nauman",
	"Process Art",
	"Process Art Influence",
	"Influenced by David Park",
	"Influenced by Jackson Pollock",
	"Influenced by Wassily Kandinsky",
	"Influenced by Joseph Beuys",
	"Love",
	"Post-World War I European Classicism",
	"Influenced by Robert Smithson",
	"Influenced by Edward Hopper",
	"Influenced by Ansel Adams",
	"Influenced by Jean-François Millet",
	"Traditional Scroll Painting",
	"Political Pop",
	"Cynical Realism",
	"'85 New Wave",
	"Traditional Scroll Painting Influence",
	"Spatialism",
	"Spatialism Influence",
	"Influenced by Georges Seurat",
	"Influenced by Kurt Schwitters",
	"The Blue Rider",
	"The Blue Rider Influence",
	"Influenced by Georges Braque",
	"Nul Group",
	"Nul Group Influence",
	"Influenced by Robert Delaunay",
	"Literature",
	"'85 New Wave Influence",
	"Vienna Secession",
	"Vienna Secession Influence",
	"American Regionalism",
	"American Regionalism Influence",
	"Influenced by Francis Bacon",
	"Happenings",
	"Happenings Influence",
	"Influenced by David Smith",
	"Art Brut",
	"Art Brut Influence",
	"Influenced by Julio González",
	"Influenced by Robert Morris",
	"Food",
	"Influenced by Louise Bourgeois",
	"Color Theory",
	"Influenced by Martin Munkácsi",
	"Influenced by Joseph Cornell",
	"Race",
	"Contemporary Feminist",
	"Political Minimalism/Conceptualism",
	"Influenced by Paul Gauguin",
	"Influenced by Michelangelo",
	"Austrian and German Expressionism",
	"Austrian and German Expressionism Influence",
	"Influenced by Robert Ryman",
	"Influenced by Brice Marden",
	"Influenced by Donald Judd",
	"Influenced by Dan Flavin",
	"Capitalist Realism",
	"Capitalist Realism Influence",
	"Influenced by Edward Weston",
	"Land Art",
	"Influenced by Morris Louis",
	"Influenced by Edvard Munch",
	"Influenced by Laszlo-Moholy Nagy",
	"Influenced by Andrew Wyeth",
	"Sports/Athletics",
	"Repetition",
	"Gestural",
	"Model/Maquette",
	"Animation",
	"Influenced by Sigmar Polke",
	"Influenced by Robert Motherwell",
	"Influenced by Roberto Matta",
	"Influenced by Hans Hofmann",
	"Funk Art",
	"Funk Art Influence",
	"Primary Mark",
	"Primary Abstraction",
	"Sparse",
	"Decayed/Aged/Deteriorated",
	"Creased/Crinkled/Wrinkled",
	"Angular",
	"Symmetrical ",
	"Haze",
	"Color Gradient",
	"Dotted",
	"Shiny/Glossy",
	"Highly-Detailed",
	"Bright/Vivid",
	"Transparent/Translucent Medium",
	"Large Brushstrokes/Loose Brushwork",
	"Dense Composition",
	"Bulbous",
	"Sharp/Prickly",
	"Blurred ",
	"Hatching",
	"Smooth",
	"Glitter",
	"Maps/Networks",
	"Grid",
	"Influenced by Julian Schnabel",
	"Influenced by Richard Prince",
	"Influenced by Jeff Koons",
	"Influenced by Cy Twombly",
	"Related to Toys",
	"Influenced by Claude Monet",
	"Influenced by Richard Serra",
	"Influenced by Francisco de Goya",
	"Influenced by Caravaggio",
	"Film/Video",
	"Influenced by Alexander Calder",
	"Movement",
	"Computer Art",
	"Contemporary Ceramics",
	"Influenced by Franz Kline",
	"Influenced by Joseph Stella",
	"Influenced by Wayne Thiebaud",
	"Influenced by Raphaelle Peale",
	"Personal Histories",
	"United Kingdom and Ireland",
	"Influenced by Clyfford Still",
	"Influenced by Giorgio Morandi",
	"Long Exposure",
	"Related to Music",
	"Encaustic",
	"Intentionally Exposed Canvas",
	"Stains/Washes",
	"Primary Colors",
	"Large-Scale Photography",
	"Camera Obscura",
	"Urbanization",
	"City Life",
	"Influenced by Fernand Leger",
	"Influenced by Johannes Vermeer",
	"Street Art",
	"Graffiti",
	"Influenced by Robert Frank",
	"Suspended/Hanging",
	"Group of Portraits",
	"Conceptual Portraiture",
	"Individual Portrait",
	"Pop Art",
	"Disaster",
	"Chance",
	"Contemporary Participation",
	"Scenes of Everyday Life",
	"Immersive ",
	"Culture Critique",
	"Contemporary Pop",
	"Diaristic Photography",
	"The Fantastic",
	"Hard-Edged",
	"Molecular",
	"Photo-abstraction",
	"Stolen Moments",
	"Unsettling",
	"Patterns",
	"Pixelated",
	"High Contrast",
	"Engagement with Mass Media",
	"Reflections",
	"Sound Art",
	"Sound",
	"Topographic Photography",
	"Obsessive",
	"Germany and Austria",
	"Western Europe",
	"United States",
	"China",
	"Russia",
	"Australia and New Zealand",
	"Southern Africa",
	"India",
	"Cuba",
	"Latin America",
	"Canada",
	"Switzerland",
	"Eastern Europe",
	"Scandinavia",
	"France",
	"South Korea",
	"Italy",
	"Japan",
	"Middle East",
	"Northern Africa",
	"South America",
	"Spain",
	"Sub-Saharan Africa",
	"Southeast Asia",
	"The Netherlands",
	"Provocative",
	"Decorative",
	"Influenced by Thomas Cole",
	"Ink-and-Wash Painting",
	"Use of Common Materials",
	"Metaphor/Allegory",
	"Myth/Religion",
	"Travel/Tourism",
	"Influenced by Paul Strand",
	"War",
	"Influenced by James Abbott McNeill Whistler",
	"Influenced by Vito Acconci",
	"The Performing Arts",
	"Language",
	"Focus on Materials",
	"Emphasis on Formal Elements",
	"CoBrA",
	"Influenced by Joan Mitchell",
	"Post-'70s Ego Generation",
	"Infographics",
	"Related to Film",
	"Cinematic",
	"Stylistic Pastiche",
	"Photographic Source",
	"Private Spaces",
	"Contemporary Portraiture",
	"Multiple Exposure",
	"Monochrome Painting",
	"Burned/Charred",
	"Interactive",
	"Influenced by Eadweard Muybridge",
	"Cross-Cultural Dialogue",
	"Representation of Everyday Objects",
	"Circus/Carnival",
	"Translucent Layers",
	"New Topographics",
	"New Topographics Influence",
	"Influenced by August Sander",
	"Zaire School of Popular Painting",
	"Cut/Ripped",
	"Influenced by Andreas Gursky",
	"Nonlinear Narrative",
	"Multiple Screens",
	"Surveillance",
	"Influenced by Auguste Rodin",
	"Silkscreen/Screenprint",
	"Large-Scale Sculpture",
	"Slow Motion",
	"Wavelet Decomp (0, 0) Saturation",
	"Wavelet Decomp (0, 0) Luminosity",
	"Wavelet Decomp (0, 1) Saturation",
	"Wavelet Decomp (0, 1) Luminosity",
	"Wavelet Decomp (0, 2) Saturation",
	"Wavelet Decomp (0, 2) Luminosity",
	"Wavelet Decomp (0, 3) Saturation",
	"Wavelet Decomp (0, 3) Luminosity",
	"Wavelet Decomp (1, 0) Saturation",
	"Wavelet Decomp (1, 0) Luminosity",
	"Wavelet Decomp (1, 1) Saturation",
	"Wavelet Decomp (1, 1) Luminosity",
	"Wavelet Decomp (1, 2) Saturation",
	"Wavelet Decomp (1, 2) Luminosity",
	"Wavelet Decomp (1, 3) Saturation",
	"Wavelet Decomp (1, 3) Luminosity",
	"Wavelet Decomp (2, 0) Saturation",
	"Wavelet Decomp (2, 0) Luminosity",
	"Wavelet Decomp (2, 1) Saturation",
	"Wavelet Decomp (2, 1) Luminosity",
	"Wavelet Decomp (2, 2) Saturation",
	"Wavelet Decomp (2, 2) Luminosity",
	"Wavelet Decomp (2, 3) Saturation",
	"Wavelet Decomp (2, 3) Luminosity",
	"Wavelet Decomp (3, 0) Saturation",
	"Wavelet Decomp (3, 0) Luminosity",
	"Wavelet Decomp (3, 1) Saturation",
	"Wavelet Decomp (3, 1) Luminosity",
	"Wavelet Decomp (3, 2) Saturation",
	"Wavelet Decomp (3, 2) Luminosity",
	"Wavelet Decomp (3, 3) Saturation",
	"Wavelet Decomp (3, 3) Luminosity",
	"Influenced by Yvonne Rainer",
	"Influenced by Marcel Broodthaers",
	"Influenced by Gordon Matta-Clark",
	"Influenced by John Martin",
	"Dau Al Set",
	"Typography",
	"Influenced by Stuart Davis",
	"Influenced by John Graham",
	"Single Object",
	"Collective History",
	"Art That Plays With Scale",
	"Influenced by Blinky Palermo",
	"Influenced by Rosemarie Trockel",
	"Influenced by Joseph Mallord William Turner",
	"Influenced by Jacob Epstein",
	"Old Master Drawings and Prints",
	"Focus on the Earth/Environment",
	"Splattered/Dripped",
	"Scattered Composition",
	"Tangled Forms",
	"Influenced by Camille Pissarro",
	"Influenced by Anthony Caro",
	"Influenced by François Boucher",
	"Influenced by Jean-Auguste-Dominique Ingres",
	"Influenced by Vladimir Tatlin",
	"Influenced by James Rosenquist",
	"Influenced by Paul Feeley",
	"Influenced by Rufino Tamayo",
	"Influenced by Emile Bernard",
	"Diaristic",
	"Influenced by Paulo Uccello",
	"Influenced by Andrea Mantegna",
	"Influenced by Piero della Francesca",
	"Influenced by Man Ray",
	"Influenced by Max Ernst",
	"Influenced by Joan Miró",
	"Influenced by Frank Stella",
	"Influenced by Ellsworth Kelly",
	"Influenced by Richard Avedon",
	"Public Art",
	"The Body",
	"Striped",
	"Close-Up",
	"Outer Space",
	"Use of Wall",
	"Self as Subject",
	"Influenced by Sol LeWitt",
	"Influenced by John McCracken",
	"Influenced by Diego Velázquez",
	"Group Portrait",
	"Text",
	"Pre-Raphaelites",
	"Pre-Raphaelites Influence",
	"Machines",
	"Modes of Transportation",
	"Industry",
	"Hyperrealism",
	"Abstract Sculpture",
	"Die Brücke",
	"Die Brücke Influence",
	"Psychoanalysis",
	"Influenced by Edward Steichen",
	"Consumerism",
	"Flatness",
	"Black and White Photography",
	"New Leipzig School",
	"Relational Aesthetics",
	"Rococo",
	"Influenced by Arturo Martini",
	"Influenced by William Henry Jackson",
	"Influenced by Aaron Siskind",
	"Influenced by Thomas Sully",
	"Influenced by Gustave Moreau",
	"Influenced by Auguste Renoir",
	"Medieval Art",
	"Typologies",
	"Early Renaissance",
	"High Renaissance",
	"Northern Renaissance",
	"Africa",
	"Time-Lapse Cinematography",
	"Manipulated Photography",
	"Staged Photography",
	"Sculpture-Based Photography",
	"Light",
	"Light as Subject",
	"Influenced by Claes Oldenburg",
	"Influenced by Edward Kienholz",
	"Influenced by El Greco",
	"Rococo Influence",
	"Open Form Sculpture",
	"Influenced by Eva Hesse",
	"Group of Objects",
	"Bay Area Figurative Art",
	"Early Medieval Art",
	"Romanesque Art",
	"Advertising and Brands",
	"Light and Space Movement",
	"Drawing",
	"Globalization",
	"Bay Area Figurative Art Influence",
	"Site Specificity",
	"Neoclassicism",
	"Collecting",
	"Precisionism",
	"Piles/Stacks",
	"American Impressionism",
	"Contemporary Graphic Realism",
	"Contemporary Undifferentiated Abstraction",
	"Contemporary Re-creations",
	"Use of Found Objects",
	"Contemporary Engaged with the Pathetic",
	"Contemporary Surrealistic",
	"Contemporary Abstract vs Figurative",
	"Contemporary Traces of Memory",
	"Contemporary Modernist-Type Photography",
	"Contemporary Color Fields",
	"Influenced by John Chamberlain",
	"Visual Perception",
	"Contemporary Traditionalism",
	"Land Art Influence",
	"Gothic Art",
	"Pop Art Influence",
	"Saturated Color",
	"Neo-Geo",
	"American Works on Paper 1880-1950",
	"American Prints 1880-1950",
	"Mono-ha",
	"Cluj School",
	"Contemporary DIY",
	"Influenced by Maurice Denis",
	"Contemporary Social Action",
	"Neo-Conceptualism",
	"Influenced by James Ensor",
	"Influenced by Philip Guston",
	"CoBrA Influence",
	"Group Material",
	"Influenced by On Kawara",
	"Influenced by Eugène Atget",
	"Influenced by Jeff Wall",
	"Obsolescence",
	"Dusseldorf School of Photography",
	"Artist as Ethnographer",
	"The New Fauves",
	"1960s/1970s German Painters",
	"Northern Renaissance Influence",
	"Early Renaissance Influence",
	"High Renaissance Influence",
	"Mono-ha Influence",
	"Gothic Art Influence",
	"American Impressionism Influence",
	"Influenced by Dale Chihuly",
	"American Sculpture 1830-1950",
	"Influenced by Grant Wood",
	"Matisse/Picasso",
	"Influenced by Kitagawa Utamaro",
	"Influenced by Sir George Beaumont",
	"Cluj School Influence",
	"Cynical Realism Influence",
	"Dau Al Set Influence",
	"Dusseldorf School of Photography Influence",
	"Early Medieval Art Influence",
	"Medieval Art Influence",
	"Neo-Geo Influence",
	"Neoclassicism Influence",
	"New Leipzig School Influence",
	"Political Pop Influence",
	"Precisionism Influence",
	"Romanesque Art Influence",
	"The New Fauves Influence",
	"Zaire School of Popular Painting Influence",
	"Influenced by Edouard Vuillard",
	"Influenced by Raoul Hausmann",
	"Influenced by Camille Corot",
	"Influenced by Nicolas Poussin",
	"Influenced by David Alfaro Siqueiros",
	"Influenced by Max Beckmann",
	"Influenced by Helen Frankenthaler",
	"Influenced by Kenneth Noland",
	"Influenced Eadweard Muybridge",
	"Influenced by George Bellows",
	"Influenced by Richard Diebenkorn",
	"Influenced by Adolph Gottlieb",
	"Influenced by Milton Avery",
	"Influenced by Umberto Boccioni",
	"Influenced by Amadeo Modigliani",
	"Influenced by Lyonel Feininger",
	"Influenced by Johannes Itten",
	"Influenced by Alexej von Jawlensky",
	"Photomontage",
	"Photogram",
	"Street Photography",
	"Snapshot Aesthetic",
	"Focus on the Social Margins",
	"Violence",
	"Influenced by Robert Irwin",
	"Photographs of Surfaces",
	"Extreme Angle",
	"Contemporary Fact versus Fiction",
	"Influenced by Jean-Michel Basquiat",
	"Architecture",
	"Influenced by Rogier van der Weyden",
	"Influenced by Jan van Eyck",
	"Influenced by Antoine Watteau",
	"Influenced by William Hogarth",
	"Influenced by Diego Rivera",
	"New British Sculpture",
	"Influenced by Henry Moore",
	"Influenced by Titian",
	"Christian Art",
	"Grand Manner",
	"Influenced by Frida Kahlo",
	"Influenced by Antonio Canova",
	"Influenced by Leigh Bowery",
	"Generative Art",
	"Website",
	"Chicago Imagists",
	"Influenced by Benjamin West",
	"Influenced by Cimabue",
	"Influenced by Henri Rousseau",
	"Influenced by Peter Paul Rubens",
	"Influenced by Georg Baselitz",
	"Influenced by Rudolf Steiner",
	"Influenced by Frank Lloyd Wright",
	"Art and Technology",
	"Shallow Depth of Field",
	"Shadows",
	"Negative Image",
	"Aerial Photography",
	"Influenced by Raphael",
	"Influenced by Hendrick ter Brugghen",
	"Influenced by Theo Van Doesburg",
	"Influenced by George Grosz",
	"Influenced by Chaïm Soutine",
	"Influenced by Nancy Spero",
	"Influenced by Kiki Smith",
	"Influenced by Judy Pfaff",
	"Abstract Painting",
	"Figurative Painting",
	"Post-Painterly Abstraction",
	"Net Art",
	"Influenced by Giacomo Balla",
	"Influenced by Conrad Marca-Relli",
	"Influenced by Honoré-Victorin Daumier",
	"Influenced by Eugène Delacroix",
	"Influenced by Giotto Di Bondone",
	"The Art Market",
	"Influenced by René Magritte",
	"The Abject",
	"Mutated Body",
	"Influenced by William Eggleston",
	"Influenced by Yves Klein",
	"Influenced by Gabriel Orozco",
	"New American Color Photography",
	"Influenced by Frank Auerbach",
	"Influenced by Roy Lichtenstein",
	"Glitch Aesthetic",
	"Influenced by Hans Haacke",
	"Influenced by Raymond Pettibon",
	"Influenced by Hannah Höch",
	"Influenced by Jean Metzinger",
	"Entertainment",
	"Leisure",
	"Science",
	"Math",
	"Relief",
	"Watercolor",
	"Influenced by Juan Gris",
	"Korea",
	"Influenced by Martin Kippenberger",
	"Influenced by Albert Oehlen",
	"Influenced by Ad Reinhardt",
	"Influenced by Pauline Boty",
	"Influenced by Pieter Bruegel the Elder",
	"Influenced by Franz West",
	"Influenced by Persian Miniatures",
	"Influenced by Hieronymus Bosch",
	"Influenced by Caspar David Friedrich",
	"Influenced by Jacques-Louis David",
	"Influenced by Gabriele Rossetti",
	"Influenced by Christopher Wool",
	"Curvilinear Forms",
	"Irregular Curvilinear Forms",
	"Mirrored",
	"Contemporary Vintage Photography",
	"Irregular Linear Forms",
	"Cloisonnism",
	"Pulled/Scraped",
	"Fluid Forms",
	"Fractured Geometry",
	"Influenced by Johann Christian Reinhart",
	"Influenced by Joseph Anton Koch",
	"Influenced by John Ruskin",
	"Influenced by Horst P Horst",
	"Influenced by Clara Peeters",
	"Animal Portrait",
	"Nazarene Movement Influence ",
	"Influenced by Alexander Gardner ",
	"Influenced by William Holman Hunt ",
	"Influenced by Ford Maddox Brown ",
	"Related to Games",
	"Influenced by Lucas Cranach the Elder",
	"Influenced by Barbara Hepworth",
	"Influenced by Arthur Dove",
	"Influenced by William Bailey",
	"Trompe l’oeil",
	"Influenced by Hiroshi Sugimoto",
	"Influenced by Lee Friedlander ",
	"Use of Printed Matter",
	"Neue Figuration Influence ",
	"Visual References",
	"Figures of the Art World",
	"Spaces of the Art World",
	"Concrete Art",
	"Influenced by Le Corbusier",
	"Influenced by Max Bill",
	"Orphism",
	"South Asia",
	"Central Asia",
	"Aboriginal Art",
	"Influenced by Mario Merz",
	"Influenced by Michelangelo Pistoletto",
	"Influenced by Lucio Fontana",
	"Influenced by Agnes Martin",
	"Influenced by Alberto Burri",
	"Old Masters",
	"Modern and Impressionist Art",
	"20th Century Art",
	"Post-War American Art",
	"Art of the 1960s",
	"Art of the 1990s",
	"Contemporary Chinese Art",
	"Emerging Art",
	"Women Artists",
	"Contemporary Photography",
	"Water",
	"Art After 2000",
	"Serenity",
	"Neo-Concrete Art",
	"Syrian Art",
	"Iranian Art",
	"Manuscript",
	"Egyptian Art",
	"Roman Art",
	"Greek Art",
	"Aztec Art",
	"Mayan Art",
	"Etruscan Art",
	"Phoenician Art",
	"Carolingian Art",
	"Coptic Art",
	"Ottoman Art",
	"Mughal Art",
	"Islamic Art",
	"Influenced by Paul Delaroche",
	"Influenced by Felix Gonzalez-Torres",
	"Influenced by John Flaxman",
	"Influenced by Thomas Hart Benton",
	"Royalty/Aristocracy",
	"Royal/Court Commission",
	"Abstract Landscape",
	"Hellenistic Art",
	"Brutalism",
	"Neo-Plasticism",
	"Pastel",
	"Artists' Books",
	"Crown/Church Commission",
	"Influenced by Peter Halley",
	"Turkey",
	"Benelux",
	"Greece",
	"Iran",
	"Edo Art",
	"Edo Art Influence",
	"Mexico",
	"Influenced by John Constable",
	"Portugal",
	"Belgium",
	"Contemporary Latin American Art",
	"Contemporary British Art",
	"Oil Painting",
	"Abstract Art",
	"Contemporary Asian Art",
	"Graffiti/Street Art",
	"Influenced by Masaccio",
	"Influenced by Fra Angelico",
	"Influenced by Alex Katz",
	"Contemporary African Art",
	"California Art",
	"Contemporary Indian Art",
	"19th Century American Art",
	"Print",
	"Influenced by Gustav Klimt",
	"Influenced by William Klein",
	"Influenced by Shōmei Tōmatsu",
	"Influenced by Romare Bearden",
	"Abstract versus Figurative",
	"Yombe Art",
	"Iban Art",
	"Balinese Art",
	"Benin Art",
	"Hopi Art",
	"Papua New Guinea Art",
	"Indian Art",
	"Luba Art",
	"Mangbetu Art",
	"Taiwanese Art",
	"Yoruba Art",
	"Bamileke Art",
	"Indonesian Art",
	"Mende Art",
	"Kanuri Art",
	"Tsimshian Art",
	"Asante Art",
	"Art of Burma",
	"Oku Art",
	"Art of the Ivory Coast",
	"Moche Art",
	"Maranao Art",
	"Guatemalan Art",
	"Art of Tonga",
	"Mbole Art",
	"Yaka Art",
	"Art of the Congo",
	"Haida Art",
	"Post-World War II School of Paris",
	"Western Zhou Dynasty",
	"Eastern Zhou Dynasty",
	"Influenced by Thomas Eakins",
	"Contemporary Middle Eastern Art",
	"Influenced by Jacopo Bellini",
	"Influenced by Filippo Brunelleschi",
	"Influenced by Donatello",
	"Influenced by Leon Battista Alberti",
	"Caricature / Parody",
	"The Afterlife",
	"Antiquity as Subject",
	"Ceremonial Object",
	"East Asian Art of Silk/Art on Silk",
	"East Asian Calligraphy",
	"Arabic/Farsi Calligraphy",
	"Jin Dynasty",
	"Ming Dynasty",
	"Song Dynasty",
	"Qing Dynasty",
	"Influenced by Victor Horta",
	"Yuan Dynasty",
	"East Asian Calligraphy Influence",
	"Venetian School",
	"Venetian School Influence ",
	"Art of the Upper Paleolithic",
	"Parties and Celebrations",
	"Decadence",
	"Bronze",
	"Primitivism Influence",
	"Buddhist Art ",
	"Related to Religion",
	"New Mythologies",
	"Classical Mythology",
	"Southeast Europe",
	"19th Century American Paintings and Works on Paper",
	"Song Dynasty Influence",
	"Spirituality of Nature",
	"Kushan Empire",
	"Sui Dynasty",
	"Influenced by Sandro Botticelli ",
	"Influenced by Daido Moriyama",
	"Influenced by Jörg Immendorff",
	"Influenced by Markus Lüpertz",
	"Influenced by Andrea Verrocchio",
	"Minoan Art",
	"Mycenaean Art",
	"American Mid-Century Design",
	"American Studio Craft Movement",
	"Israel",
	"Influenced by Marco Ricci",
	"Caucasus",
	"Post-War European Art",
	"Chair",
	"Table",
	"Wood",
	"Furniture",
	"Armchair",
	"Side Chair",
	"Dining Table",
	"Side Table",
	"Chaise Lounge",
	"Bed",
	"Storage",
	"Vessel",
	"Bowl",
	"Vase",
	"Tray",
	"Tapestry",
	"Rug",
	"Lighting",
	"Floor Lamp",
	"Table Lamp",
	"Ceiling Light",
	"Jewelry",
	"Flatware",
	"Objet de Vertu",
	"Plastic",
	"Silver",
	"Chrome-Plated",
	"Upholstery",
	"Wallpaper",
	"Post-war French Design",
	"Postmodern Architecture & Design",
	"Design/Architecture Study",
	"Tableware",
	"Influenced by Gentile da Fabriano",
	"Musical Instrument",
	"Door",
	"Door Hardware",
	"Desk",
	"Arms and Armor",
	"Poster",
	"Influenced by Pietro Perugino",
	"Mirror",
	"The Aesthetic Movement",
	"Natural Forms",
	"Iridescence/Opalescence",
	"Western Calligraphy",
	"Steel",
	"Patinated/Oxidized/Verdigris",
	"Color Photography",
	"The Altered Canvas",
	"Marbleized",
	"Sofa",
	"Unspecified Metal",
	"Influenced by Kenny Sharf",
	"Influenced by Yayoi Kusama",
	"1980s famous artists",
	"Influenced by Gregory Crewdson",
	"Influenced by Philip-Lorca diCorcia",
	"Linear Forms",
	"American Modern Design",
	"Influenced by James VanDerZee",
	"Influenced by Irving Penn",
	"Egyptian Art Influence",
	"Tablet/Stele",
	"Funerary Object",
	"Unspecified Stone",
	"Celtic Art ",
	"Mesopotamian Art ",
	"Marble",
	"Greek Art Influence ",
	"Tool",
	"Tang Dynasty",
	"Gemstone",
	"Contemporary History Painting",
	"Influenced by Ludwig Mies Van Der Rohe",
	"Influenced by Walter Gropius",
	"Influenced by Peter Behrens",
	"Gold",
	"Clock",
	"Influenced by Emil Nolde",
	"Bench",
	"Influenced by Nicolas de Staël",
	"Influenced by Antoni Tàpies",
	"New American Documentary Photography",
	"Influenced by Bruno Taut",
	"Neo-Concrete Influence",
	"Aluminum",
	"Concrete/Cement",
	"Hellenistic Art Influence",
	"Influenced by Claude Lorrain",
	"Ancient Art/Artifact",
	"Mesopotamian Art Influence",
	"Contemporary Realist Portraiture",
	"Influenced by Dorthea Tanning",
	"Cambodian Art ",
	"Thai Art ",
	"Hindu Art",
	"Intaglio",
	"Etching/Engraving",
	"Lithograph",
	"Monotype/Monoprint",
	"Transfer",
	"Porcelain",
	"Influenced by Paul Sérusier",
	"Influenced by Jean-Michel Frank",
	"Metal",
	"Ceramic",
	"Stone",
	"Influenced by William Merritt Chase ",
	"Digital Print",
	"Influenced by Alexander Archipenko",
	"Religious Building",
	"Monument",
	"International Style ",
	"Deconstructivism",
	"Organic Architecture ",
	"Sustainability",
	"Textiles",
	"Meiji Art",
	"Influenced by Oscar Niemeyer",
	"Influenced by Thomas Ruff",
	"Influenced by Cindy Sherman",
	"History Painting",
	"Work and Workers",
	"Influenced by Anselm Kiefer",
	"Influenced by Giovanni Battista Piranesi",
	"International Style Influence",
	"Influenced by Ross Bleckner",
	"Influenced by François Girardon",
	"Ivory",
	"Roman Art Influence",
	"Etruscan Art Influence",
	"Influenced by Paul McCarthy",
	"Influenced by Naum Gabo",
	"Influenced by Gio Ponti",
	"Influenced by Claude and Françoise Lalanne",
	"Influenced by Ben Nicholson",
	"Influenced by Dagobert Peche",
	"Influenced by William Morris",
	"Influenced by Josef Hoffmann",
	"Influenced by Michael Thonet",
	"Fragment ",
	"Influenced by Charles and Ray Eames",
	"Influenced by George Nelson",
	"Union des Artistes Modernes",
	"Union des Artistes Modernes Influence",
	"Influenced by Pierre Bonnard",
	"Influenced by George Nakashima",
	"Influenced by Wharton Esherick",
	"Influenced by Sam Maloof",
	"Influenced by Ettore Sottsass",
	"Influenced by Bruno Mathsson",
	"Enamel",
	"Natural Fibers",
	"Inlay",
	"Stool",
	"3D Printed",
	"Laminated",
	"Extruded",
	"Continuous Form",
	"Asymmetrical",
	"Radiating Lines",
	"Slender",
	"Woven/Perforated",
	"Whimsical Design",
	"Craftsmanship and Design",
	"Engineering/Construction and Design",
	"Influenced by Duccio di Buoninsegna",
	"Influenced by Sonia Delaunay",
	"Central America",
	"Influenced by Zaha Hadid",
	"Influenced by Carlo Scarpa",
	"Influenced by Archigram",
	"Rationalism Influence",
	"Influenced by Ernst Haeckel",
	"Influenced by Scott Burton",
	"Influenced by Enzo Mari",
	"Influenced by Gerrit Rietveld",
	"Influenced by Rudolph Schindler",
	"Influenced by Otto Herbert Hajek",
	"Resin",
	"Shang Dynasty ",
	"Influenced by Charlotte Perriand",
	"Pre-World War II School of Paris",
	"Bathers",
	"Crowd",
	"Domestic Scene",
	"Face",
	"Family",
	"Imaginary Creatures",
	"Figure Study",
	"Figures Outdoors",
	"Overlapping/Interlaced/Contorted Bodies",
	"Intimate Moments/Embraces",
	"Body Parts",
	"Classical Figure",
	"Attenuated Figure",
	"Political Event",
	"Influenced by Florine Stettheimer",
	"Kota Art ",
	"Joseon Dynasty ",
	"Igbo (Ibo) Art ",
	"Black Mountain College",
	"Students of Hans Hofmann",
	"Students of Michael Craig-Martin",
	"Influenced by Andrea Palladio",
	"Students of Joseph Beuys",
	"New New York School",
	"Based in Berlin",
	"Based in Brooklyn",
	"33 and Under",
	"Miniature Paintings",
	"Yale University School of Art",
	"Influenced by Henri de Toulouse-Lautrec",
	"Influenced by Jean-Louis-André-Théodore Gericault",
	"Pre-Columbian",
	"Pre-Columbian Influence",
	"Influenced by Jean-Honoré Fragonard",
	"Taiwan",
	"Islamic Art Influence",
	"Influenced by Alvar Aalto",
	"Victorian Architecture ",
	"Influenced by Lawrence Weiner",
	"Influenced by Joseph Kosuth",
	"Aboriginal Art Influence",
	"Influenced by Francisco de Zurbarán",
	"Influenced by Giovanna Garzoni",
	"Influenced by Adriaen Coorte",
	"Droog Design Influence",
	"Madonna and Child ",
	"Military ",
	"The Seasons ",
	"Saints ",
	"Seduction and Courtship",
	"Bible Story ",
	"Equestrian ",
	"Sfumato ",
	"Emphasis on Linear Perspective ",
	"Caravaggesque",
	"Rembrandtesque ",
	"Tondo",
	"Oil on Panel ",
	"Oil on Copper ",
	"Tempera ",
	"Gold Ground ",
	"Altarpiece ",
	"Terracotta ",
	"Chalk",
	"Influenced by Carlo Mollino",
	"Influenced by Arne Jacobsen",
	"Influenced by Mathieu Matégot",
	"Influenced by Hella Jongerius",
	"Carlo Mollino Influence",
	"Influenced by Francesco Guardi",
	"Influenced by Francesco Pittoni",
	"Influenced by Hans Holbein",
	"Influenced by Lodovico Cigoli",
	"Influenced by Giambattista Tiepolo",
	"Influenced by Gian Lorenzo Bernini",
	"Influenced by Domenico Zampieri, Domenichino",
	"Influenced by Charles Le Brun",
	"Influenced by Girolamo Francesco Maria Mazzola, il Parmigianino",
	"Influenced by Antonio Allegri da Correggio",
	"Influenced by Girolamo da Carpi",
	"Influenced by Girolamo Mazzola Bedoli",
	"Influenced by Pietro Berrettini, called Pietro da Cortona",
	"Influenced by Joseph Vernet",
	"Influenced by Jacopo Tintoretto",
	"Influenced by Giovanni Bellini",
	"Influenced by Giorgione",
	"Influenced by Antoine-Jean Gros",
	"Influenced by José de Ribera",
	"Influenced by Pontormo",
	"Influenced by Fra Bartolommeo",
	"Influenced by Thomas Gainsborough",
	"Influenced by Sir Anthony van Dyck",
	"OMP - Renaissance",
	"OMP - Old Master Paintings Part II",
	"OMP - Old Master Drawings",
	"OMP - Old Master Paintings Part I",
	"OMP - Albrecht Dürer - Masterpieces from a Private Collection",
	"Influenced by Terra Fuller",
	"Art",
	"Influenced by Alfred Boucher",
	"Influenced by Jean Tinguely",
	"Influenced by Jean-Baptiste-Siméon Chardin",
	"Influenced by Allan Kaprow",
	"Influenced by Carlos Cruz-Diez",
	"Influenced by Jesus Rafael Soto",
	"Influenced by Alejandro Otero",
	"Cardboard",
	"Influenced by Buckminster Fuller",
	"Influenced by Fred Holland Day",
	"Chosŏn dynasty",
	"Influenced by Georgia O'Keeffe",
	"Concrete Art Influence",
	"Contemporary Faux Naïf",
	"Still House Group",
	"The Armory Show 1913 Archival Documents",
	"Influenced by Michael Asher",
	"Influenced by David Hockney",
	"Influenced by Ingmar Bergman",
	"Influenced by Ferdinand Hodler",
	"Carving",
	"Influenced by Keith Haring",
	"Traces",
	"Figuration: Post-War to the Present",
	"Black Arts Movement",
	"Influenced by James Turrell",
	"Influenced by Georges Méliès",
	"Influenced by Buster Keaton",
	"Influenced by Sergio Rodrigues",
	"Joseon Dynasty Influence",
	"Biedermeier",
	"Biedermeier Influence",
	"Influenced by Nick Cave",
	"Diptych",
	"Triptych",
	"Dark LAB DO NOT USE",
	"Bright/Vivid LAB GENE DO NOT USE",
	"Mughal Art Influence",
	"Bengal School of Art",
	"Bengal School of Art Influence",
	"Progressive Artists' Movement",
	"Asia Week",
	"Aesthetic Movement Influence",
	"Influenced by Henry van de Velde",
	"Influenced by Alphonse Mucha",
	"Influenced by Hermann Obrist",
	"Heian period",
	"Influenced by Mel Ramos",
	"Influenced by Armand-Albert Rateau",
	"The Fantastical",
	"Western Africa",
	"Eastern Africa",
	"Middle Africa",
	"Influenced by Elger Esser",
	"Influenced by Richard Misrach",
	"Influenced by Stephen Shore",
	"Bone",
	"Pop Art and Contemporary Pop",
	"Color Field Painting and Contemporary Color Fields",
	"Conceptual Art and Contemporary Conceptualism",
	"South Africa",
	"Influenced by Eastern Thought",
	"Old Masters and Contemporary Traditionalism",
	"Die Brücke Influence",
	"Extruded",
	"Objet de Vertu",
	"The Altered Canvas",
	"Photo-abstraction",
	"Stylistic Pastiche",
	"Gallery Weekend Berlin",
	"High CSG",
	"Low CSG"
]